// <auto-generated />
using System;
using BaseApi.Infrastructure.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817224906_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BaseApi.Domain.Entidades.DadosSecretaria", b =>
                {
                    b.Property<Guid>("SecretariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Endereço")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("SecretariaId");

                    b.ToTable("dados_secretaria", (string)null);

                    b.HasData(
                        new
                        {
                            SecretariaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Bairro = "Palmital",
                            Cep = "29906-725",
                            Cidade = "Linhares",
                            Contato = "(27) 98105-0171",
                            Email = "semel@linhares.es.gov.br",
                            Endereço = "Av. Roberto Marinho",
                            Nome = "Secretaria Municipal de Esporte e Lazer",
                            Numero = "306"
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.DataHorarioReserva", b =>
                {
                    b.Property<Guid>("DataHorarioReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<Guid>("QuadraId")
                        .HasColumnType("char(36)");

                    b.HasKey("DataHorarioReservaId");

                    b.HasIndex("QuadraId", "Data", "Horario")
                        .IsUnique();

                    b.ToTable("data_horario_reservas", (string)null);
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("perfis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Acesso total ao sistema",
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Acesso de vigilante ao sistema",
                            Nome = "Vigilante"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Acesso básico ao sistema",
                            Nome = "Usuário"
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Quadra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("longtext");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("quadras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro São José.",
                            ImagemUrl = "https://altipisos.com.br/wp-content/uploads/2022/05/quadra-esportiva-1-1.jpeg",
                            Localizacao = "São José",
                            Modalidade = "Futebol",
                            Nome = "GINÁSIO POLIESPORTIVO \"EURICO GUILHERME SCHULZ\"",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Aviso.",
                            ImagemUrl = "https://www.juvenil.com.br/portal/imgs/textos/quadra-poliesportiva-apos-reforma1678137566.jpeg",
                            Localizacao = "Aviso",
                            Modalidade = "Futebol",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO AVISO",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Interlagos.",
                            ImagemUrl = "https://mid-noticias.curitiba.pr.gov.br/2022/00341942.jpg",
                            Localizacao = "Interlagos",
                            Modalidade = "Futebol",
                            Nome = "GINÁSIO POLIESPORTIVO \"LEANDRO SILVA DOS REIS\"",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Araçá.",
                            ImagemUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIF0n5FrisqvRa5ulciyD48kfQ1wUOBlXz-r5BO8zH7Iovgh1RIEPJOunz&s=10",
                            Localizacao = "Araçá",
                            Modalidade = "Futebol",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO ARAÇÁ",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Conceição.",
                            ImagemUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3_cuXIPJxJTR-aLEquO3IGEhZbaTbaLB_mOY_tKEW0xJKTo_SNVckXLna&s=10",
                            Localizacao = "Conceição",
                            Modalidade = "Futebol",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO CONCEIÇÃO",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Shell.",
                            ImagemUrl = "https://psd.org.br/wp-content/uploads/2023/11/Quadra-do-Jardim-Figueiras.-Divulgacao-Prefeitura-de-Valinhos.jpg",
                            Localizacao = "Shell",
                            Modalidade = "Futsal",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO SHELL",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Canivete.",
                            ImagemUrl = "https://www.sescpr.com.br/wp-content/uploads/2020/11/20201001_173756.jpg",
                            Localizacao = "Canivete",
                            Modalidade = "Basquete",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO CANIVETE",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Novo Horizonte.",
                            ImagemUrl = "https://img.magnific.com/fotos-gratis/quadra-de-tenis-interna_1385-1396.jpg",
                            Localizacao = "Novo Horizonte",
                            Modalidade = "Vôlei",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO NOVO HORIZONTE",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Jardim Laguna.",
                            ImagemUrl = "https://tenisclubepaulista.com/wp-content/uploads/2023/03/quadra-beach-tennis.jpeg",
                            Localizacao = "Jardim Laguna",
                            Modalidade = "Beach Tennis",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO JARDIM LAGUNA",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Movelar.",
                            ImagemUrl = "https://nprpinturasereformas.com.br/wp-content/uploads/2022/09/Pinturas-e-Reformas-de-Quadras-Poliesportivas-12-3.jpeg",
                            Localizacao = "Movelar",
                            Modalidade = "Handebol",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO MOVELAR",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Três Barras.",
                            ImagemUrl = "https://urupes.sp.gov.br/noticias/upload/postagens/1715802666_32167.jpg",
                            Localizacao = "Três Barras",
                            Modalidade = "Futebol",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO TRÊS BARRAS",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Santa Cruz.",
                            ImagemUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN_q4bBB3iBwSsrFh5nsqEuJhIuXRJmn8jjpDmy57QCy1wx_nqOeKQ0GE&s=10",
                            Localizacao = "Santa Cruz",
                            Modalidade = "Basquete",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO SANTA CRUZ",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Planalto.",
                            ImagemUrl = "https://harmoniaclubedecampo.com.br/img/esportes/g/harmoniaclubedecampo_esportes_15102025_155937_0001.jpg",
                            Localizacao = "Planalto",
                            Modalidade = "Vôlei",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO PLANALTO",
                            Status = "Ativa"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Capacidade = 20,
                            Descricao = "Ginásio Poliesportivo localizado no bairro Lagoa do Meio.",
                            ImagemUrl = "https://media-cdn.tripadvisor.com/media/photo-s/14/bc/5b/b9/futsal-and-basketball.jpg",
                            Localizacao = "Lagoa do Meio",
                            Modalidade = "Futsal",
                            Nome = "GINÁSIO POLIESPORTIVO BAIRRO LAGOA DO MEIO",
                            Status = "Ativa"
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Reserva", b =>
                {
                    b.Property<Guid>("ReservasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HorarioAgendado")
                        .HasColumnType("time");

                    b.Property<Guid>("QuadraId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("ReservasId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("QuadraId", "DataAgendada", "HorarioAgendado")
                        .IsUnique();

                    b.ToTable("reservas", (string)null);

                    b.HasData(
                        new
                        {
                            ReservasId = new Guid("70000000-0000-0000-0000-000000000001"),
                            DataAgendada = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HorarioAgendado = new TimeSpan(0, 8, 0, 0, 0),
                            QuadraId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Ativa",
                            UsuarioId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ReservasId = new Guid("70000000-0000-0000-0000-000000000002"),
                            DataAgendada = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HorarioAgendado = new TimeSpan(0, 9, 0, 0, 0),
                            QuadraId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Ativa",
                            UsuarioId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ReservasId = new Guid("70000000-0000-0000-0000-000000000003"),
                            DataAgendada = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HorarioAgendado = new TimeSpan(0, 10, 0, 0, 0),
                            QuadraId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Status = "Ativa",
                            UsuarioId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ReservasId = new Guid("70000000-0000-0000-0000-000000000004"),
                            DataAgendada = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HorarioAgendado = new TimeSpan(0, 11, 0, 0, 0),
                            QuadraId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Status = "Ativa",
                            UsuarioId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ReservasId = new Guid("70000000-0000-0000-0000-000000000005"),
                            DataAgendada = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HorarioAgendado = new TimeSpan(0, 14, 0, 0, 0),
                            QuadraId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Status = "Ativa",
                            UsuarioId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ReservasId = new Guid("70000000-0000-0000-0000-000000000006"),
                            DataAgendada = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HorarioAgendado = new TimeSpan(0, 16, 0, 0, 0),
                            QuadraId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Status = "Ativa",
                            UsuarioId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("UsuariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UsuariosId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuariosId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cpf = "",
                            CriadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@baseapi.com",
                            NomeCompleto = "Administrador do Sistema",
                            PerfilId = 1,
                            SenhaHash = "$2a$11$OEmfV3ruyKXQL0ldgJSm6O3Tg0LUy8xB87K7WRhIh44SYdb8psWre",
                            Telefone = ""
                        },
                        new
                        {
                            UsuariosId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "12569348712",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gabrieli.arpini@gmail.com",
                            NomeCompleto = "Gabrieli Arpini",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$yYHCfB6giS5eLGIlnJL9puKeqgR0F0l/ytyUe1VSGYfm9ZiyOF.By",
                            Telefone = "27998123456"
                        },
                        new
                        {
                            UsuariosId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "38495127604",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucashenriquef@gmail.com",
                            NomeCompleto = "Lucas Henrique Ferreira",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$/wrcEU1JR8f3GtnTYdcJtulVnkjtreCFuHdMZ7OFLCDKTb7o5fhzC",
                            Telefone = "27998254731"
                        },
                        new
                        {
                            UsuariosId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "56381927401",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariana.oliveira@gmail.com",
                            NomeCompleto = "Mariana Oliveira Santos",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$bQyMwvC97Tygb9hhHOytV.QcNNglD.NZcHc2YFLxsdq7YkTDMv9sC",
                            Telefone = "27998361425"
                        },
                        new
                        {
                            UsuariosId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "71438296510",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pedro.henrique.a@gmail.com",
                            NomeCompleto = "Pedro Henrique Almeida",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$4BQmYCxM2YWULXLugu20qOIjQQy6CLjnbqy9FpjORA5k8yI8nwUBC",
                            Telefone = "27998472516"
                        },
                        new
                        {
                            UsuariosId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "29617483592",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anacarolinalima@gmail.com",
                            NomeCompleto = "Ana Carolina Lima",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$cIFfDAbHEm4teZSinw24rOo0U9NqbqGj5ppqh67cD6T0.A1EKdZX.",
                            Telefone = "27998581342"
                        },
                        new
                        {
                            UsuariosId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "84752063198",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rafael.costa@gmail.com",
                            NomeCompleto = "Rafael Costa Pereira",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$M8wfhKLP2Ja1LpN0jj2WquAso99QTttbuUHtgaBxv7oviylA8xFsq",
                            Telefone = "27998693574"
                        },
                        new
                        {
                            UsuariosId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "53069182477",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julianamartins@gmail.com",
                            NomeCompleto = "Juliana Martins Rocha",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$iz4U/Ap46YFWfjIYo2cF8uyVAtiwsTV.hdFqLofAS39lrE7PKCKLi",
                            Telefone = "27998714653"
                        },
                        new
                        {
                            UsuariosId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "18240795634",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "felipe.almeida@gmail.com",
                            NomeCompleto = "Felipe Augusto Almeida",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$5o/UZ2PqF5CXIkkkNkh/qOfKOjyjq/EzfiGbgD0dA8avbyljVmKei",
                            Telefone = "27998835791"
                        },
                        new
                        {
                            UsuariosId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "40528691375",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "beatriz.gomes@gmail.com",
                            NomeCompleto = "Beatriz Gomes da Silva",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$DfkzQPZjzLzxo0xmTjGW6ukR7RrTim0779u8dWOAydeaost0BXCby",
                            Telefone = "27998926418"
                        },
                        new
                        {
                            UsuariosId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "69135824780",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gustavo.ribeiro@gmail.com",
                            NomeCompleto = "Gustavo Ribeiro Nascimento",
                            PerfilId = 3,
                            SenhaHash = "$2a$11$mxKrMry9aarkBHROrX6OBuKUG41vkZeEom8TpMPqr83p7Bu9auBde",
                            Telefone = "27999047185"
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Vigilantes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Arena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("vigilantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Arena = "GINÁSIO POLIESPORTIVO BAIRRO AVISO",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "12345678901",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1988, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos.silva@gmail.com",
                            FotoPerfil = "https://img.magnific.com/fotos-gratis/policial-masculino-atraente-com-municao-segurando-arma-com-ambas-as-maos-vista-frontal-do-homem-barbudo-de-preto_7502-10633.jpg?semt=ais_hybrid&w=740&q=80",
                            Matricula = "VIG001",
                            NomeCompleto = "Carlos Eduardo Silva",
                            Telefone = "(11) 99523-1569"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Arena = "GINÁSIO POLIESPORTIVO BAIRRO ARAÇÁ",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "98765432100",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcos.souza@gmail.com",
                            FotoPerfil = "https://img.magnific.com/fotos-premium/jovem-guarda-de-seguranca-em-uniforme-isolado-em-branco_495423-104433.jpg?semt=ais_hybrid&w=740&q=80",
                            Matricula = "VIG002",
                            NomeCompleto = "Marcos Antônio Souza",
                            Telefone = "(11) 99821-2426"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Arena = "GINÁSIO POLIESPORTIVO LEANDRO SILVA DOS REIS",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "45678912345",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1995, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernanda.oliveira@gmail.com",
                            FotoPerfil = "https://img.magnific.com/fotos-premium/uma-policial-confiante-em-uniforme-posa-orgulhosamente-com-seu-distintivo-e-chapeu-a-luz-do-dia_489081-6667.jpg?semt=ais_hybrid&w=740&q=80",
                            Matricula = "VIG003",
                            NomeCompleto = "Fernanda Oliveira",
                            Telefone = "(11) 99201-3365"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Arena = "GINÁSIO POLIESPORTIVO INTERLAGOS",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "32165498710",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1987, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ricardo.mendes@gmail.com",
                            FotoPerfil = "https://randomuser.me/api/portraits/men/32.jpg",
                            Matricula = "VIG004",
                            NomeCompleto = "Ricardo Mendes Pereira",
                            Telefone = "(27) 99845-7132"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Arena = "GINÁSIO POLIESPORTIVO CONCEIÇÃO",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "65412378945",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1994, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juliana.rocha@gmail.com",
                            FotoPerfil = "https://gestaodesegurancaprivada.com.br/wp-content/uploads/Vigilante-feminina.jpg",
                            Matricula = "VIG005",
                            NomeCompleto = "Juliana Cristina Rocha",
                            Telefone = "(27) 99783-4621"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Arena = "GINÁSIO POLIESPORTIVO NOVO HORIZONTE",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "78945612308",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1990, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "andre.barbosa@gmail.com",
                            FotoPerfil = "https://st3.depositphotos.com/1177973/13163/i/450/depositphotos_131632566-stock-photo-security-man-standing-indoors.jpg",
                            Matricula = "VIG006",
                            NomeCompleto = "André Luiz Barbosa",
                            Telefone = "(27) 99914-5873"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Arena = "GINÁSIO POLIESPORTIVO JARDIM CAMBURI",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "95175348620",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1993, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia.almeida@gmail.com",
                            FotoPerfil = "https://partnersecurity.com.br/wp-content/uploads/2022/03/mulheres-na-seguranca-patrimonial.jpg",
                            Matricula = "VIG007",
                            NomeCompleto = "Patrícia Almeida Costa",
                            Telefone = "(27) 99872-6405"
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            Arena = "GINÁSIO POLIESPORTIVO SÃO JOSÉ",
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cpf = "85274196314",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1989, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thiago.oliveira@gmail.com",
                            FotoPerfil = "https://img.magnific.com/fotos-gratis/guarda-de-seguranca-no-espaco-de-trabalho_23-2150321639.jpg",
                            Matricula = "VIG008",
                            NomeCompleto = "Thiago Henrique Oliveira",
                            Telefone = "(27) 99751-8936"
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.DataHorarioReserva", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Quadra", null)
                        .WithMany()
                        .HasForeignKey("QuadraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Reserva", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Quadra", "Quadra")
                        .WithMany()
                        .HasForeignKey("QuadraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseApi.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quadra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
