import 'estado_central.dart';

class Tradutor {
  static final Map<String, Map<String, String>> _dicionario = {
    'Português (BR)': {
      // Geral / Comum
      'vigilante': 'VIGILANTE',
      'cancelar': 'Cancelar',
      'confirmar': 'Confirmar',
      'erro': 'Erro',
      'sucesso': 'Sucesso',
      'salvar': 'Salvar',
      'voltar': 'Voltar',
      'entendi': 'Entendi',
      'ok': 'OK',
      'liberado': 'LIBERADO',
      'pendente': 'PENDENTE',
      'livre': 'LIVRE',
      'em_uso': 'EM USO',
      'disponivel': 'DISPONÍVEL',
      'manutencao': 'MANUTENÇÃO',

      // Autenticação (Login, Cadastro, Esqueci Senha)
      'login_titulo': 'Bem-vindo de volta!',
      'login_subtitulo': 'Entre com seus dados para acessar sua conta na PlayZone.',
      'email_rotulo': 'E-mail',
      'email_dica': 'Ex: jogador@email.com',
      'senha_rotulo': 'Senha',
      'senha_dica': 'Digite sua senha de acesso',
      'esqueci_senha': 'Esqueci minha senha',
      'entrar': 'Entrar',
      'nao_tem_conta': 'Não tem uma conta?',
      'cadastre_se': 'Cadastre-se',
      'validar_email_vazio': 'Por favor, insira seu e-mail',
      'validar_email_invalido': 'Por favor, insira um e-mail válido',
      'validar_senha_vazio': 'Por favor, insira sua senha',
      'validar_senha_tamanho': 'A senha deve conter no mínimo 6 caracteres',
      
      'cadastro_titulo': 'Criar Conta',
      'cadastro_subtitulo': 'Preencha os dados abaixo para cadastrar-se como Vigilante.',
      'nome_rotulo': 'Nome Completo',
      'nome_dica': 'Digite seu nome completo',
      'matricula_rotulo': 'Matrícula',
      'matricula_dica': 'Digite o número de matrícula',
      'confirmar_senha_rotulo': 'Confirmar Senha',
      'confirmar_senha_dica': 'Digite a senha novamente',
      'cadastrar': 'Cadastrar',
      'ja_tem_conta': 'Já tem uma conta?',
      'entre': 'Entre',
      'validar_nome_vazio': 'Por favor, insira seu nome completo',
      'validar_nome_incompleto': 'Por favor, insira nome e sobrenome',
      'validar_matricula_vazio': 'Por favor, insira sua matrícula',
      'validar_matricula_numeros': 'A matrícula deve conter apenas números',
      'validar_confirmacao_vazio': 'Por favor, confirme sua senha',
      'validar_confirmacao_diferente': 'As senhas não coincidem',
      'email_ja_usado': 'Este e-mail já está sendo utilizado por outro vigilante.',
      'cadastro_realizado': 'Cadastro Realizado',
      'cadastro_sucesso_msg': 'Sua conta de vigilante foi criada com sucesso! Faça login para começar.',

      'recuperar_senha_titulo': 'Recuperar Senha',
      'recuperar_senha_subtitulo': 'Digite seu e-mail cadastrado para enviarmos as instruções de redefinição.',
      'enviar_instrucoes': 'Enviar Instruções',
      'voltar_login': 'Voltar para o login',
      'email_nao_encontrado': 'Email não encontrado',
      'email_enviado_titulo': 'E-mail Enviado',
      'email_enviado_msg': 'Email de recuperação enviado com sucesso para: {email}. Verifique sua caixa de entrada.',

      // Navegação Aba
      'aba_home': 'Home',
      'aba_buscar': 'Buscar',
      'aba_historico': 'Histórico',
      'aba_perfil': 'Perfil',

      // Home Screen
      'home_ola': 'Olá, {nome}! 👋',
      'home_pronto': 'Pronto para mais um dia de trabalho.',
      'home_escanear_qr': 'ESCANEAR\nQR CODE',
      'home_registre_entrada': 'Registre a entrada de usuários',
      'home_atalhos': 'ATALHOS DA ARENA',
      'home_controle_acesso': 'CONTROLE DE ACESSO',
      'home_gerencie_entradas': 'Gerencie e registre entradas na arena',
      'home_status_arena': 'STATUS DA ARENA',
      'home_ocupacao_quadras': 'Veja ocupação e situação das quadras',
      'home_historico_entradas': 'HISTÓRICO DE ENTRADAS',
      'home_consulte_entradas': 'Consulte todas as entradas registradas',
      'home_buscar_usuarios': 'BUSCAR USUÁRIOS',
      'home_procure_documento': 'Procure por nome ou documento (CPF)',
      'home_instrucoes': 'INSTRUÇÕES DE USO',
      'home_como_operar': 'Como operar o sistema de acessos:',
      'home_passo1': 'Abra o scanner de QR Code ao receber um jogador na entrada da quadra.',
      'home_passo2': 'Valide os dados da reserva apresentados na tela (nome do jogador, quadra e horário).',
      'home_passo3': 'Clique em \'Registrar Entrada\' para liberar o acesso e atualizar as métricas da arena.',
      'home_passo4': 'Consulte o menu \'Status da Arena\' para monitorar os clientes atualmente ativos nas quadras.',
      'home_acao_principal': 'Ação principal',
      'home_tutorial_desc': 'Use o scanner para registrar a entrada de usuários de forma rápida e segura.',

      // Buscar Screen
      'buscar_titulo': 'BUSCAR',
      'buscar_dica': 'Buscar por nome, CPF ou matrícula...',
      'buscar_resultados': 'RESULTADOS',
      'buscar_sem_resultados': 'Nenhum resultado encontrado.',

      // Histórico Screen
      'historico_titulo': 'HISTÓRICO DE ENTRADAS',
      'filtro_hoje': 'Hoje',
      'filtro_ontem': 'Ontem',
      'filtro_esta_semana': 'Esta semana',
      'filtro_todos': 'Todos',
      'historico_busca_dica': 'Buscar por nome ou quadra...',
      'historico_sem_registros': 'Nenhum registro encontrado.',

      // Perfil Screen
      'perfil_titulo': 'MEU PERFIL',
      'perfil_matricula': 'Matrícula: {matricula}',
      'perfil_configuracoes': 'Configurações',
      'perfil_notificacoes': 'Notificações',
      'perfil_sobre': 'Sobre o aplicativo',
      'perfil_sair_conta': 'Sair da conta',
      'perfil_confirmacao_titulo': 'Sair da Conta',
      'perfil_confirmacao_msg': 'Deseja realmente sair da sua conta?',
      'perfil_sair': 'Sair',

      // Notificações Screen
      'notif_titulo': 'NOTIFICAÇÕES',
      'notif_limpar_tudo': 'Limpar tudo',
      'notif_sem_novas': 'Você não tem novas notificações.',
      'notif_limpo_msg': 'Histórico de notificações limpo.',

      // Conversa / Chat Notificações
      'chat_titulo': 'CONVERSA',
      'chat_suporte': 'Suporte PlayZone',
      'chat_dica': 'Digite sua mensagem...',
      'chat_resposta_auto': 'Mensagem recebida e registrada no sistema da arena.',

      // Status Arena Screen
      'status_ocupacao_geral': 'OCUPAÇÃO GERAL',
      'status_quadras_em_uso': 'quadras em uso',
      'status_capacidade_maxima': 'CAPACIDADE MÁXIMA',
      'status_atletas_ativos': 'atletas ativos na arena',
      'status_situacao_quadras': 'SITUAÇÃO DAS QUADRAS',
      'status_horario_previsto': 'Horário previsto: {horario}',
      'status_partida_finalizada': 'Partida finalizada com sucesso.',
      'status_manutencao_msg': 'Quadra em manutenção.',
      'status_liberada_msg': 'Quadra liberada com sucesso.',
      'status_botao_liberar': 'Liberar',
      'status_botao_concluir': 'Concluir',
      'status_botao_manutencao': 'Manutenção',
      'status_botao_disponibilizar': 'Disponibilizar',

      // Perfil Detalhado Screen
      'detalhes_titulo': 'DETALHES DO JOGADOR',
      'detalhes_dados_cliente': 'DADOS DO CLIENTE',
      'detalhes_nome': 'Nome',
      'detalhes_cpf': 'CPF',
      'detalhes_matricula': 'Matrícula',
      'detalhes_local': 'Local da Reserva',
      'detalhes_horario': 'Horário Previsto',
      'detalhes_status': 'STATUS DE ACESSO',
      'detalhes_acoes': 'Ações de Acesso',
      'detalhes_btn_entrada': 'Registrar Entrada',
      'detalhes_btn_saida': 'Registrar Saída',
      'detalhes_entrada_sucesso': 'Entrada de {nome} registrada.',
      'detalhes_saida_sucesso': 'Saída de {nome} registrada.',

      // Sobre o aplicativo
      'sobre_titulo': 'SOBRE O APLICATIVO',
      'sobre_versao': 'Versão 1.2.0',
      'sobre_nome_app': 'PlayZone Vigilante',
      'sobre_descricao': 'O aplicativo PlayZone Vigilante foi desenvolvido para otimizar o controle de acesso e monitoramento em tempo real das quadras esportivas da Arena PlayZone. Com ele, a equipe de segurança pode validar ingressos via QR Code, acompanhar o status de ocupação e gerenciar a presença de atletas de forma ágil e segura.',
      'sobre_desenvolvido_por': 'DESENVOLVIDO POR',
      'sobre_equipe_ti': 'Equipe de TI PlayZone',
      'sobre_documentos': 'Documentos Legais',
      'sobre_termos': 'Termos de Uso',
      'sobre_privacidade': 'Política de Privacidade',

      // Termos de Uso
      'termos_titulo': 'TERMOS DE USO',
      'termos_atualizacao': 'Última atualização: 20/05/2026',
      'termos_secao1_tit': '1. Aceite dos Termos',
      'termos_secao1_txt': 'Ao acessar e utilizar o aplicativo PlayZone Vigilante, você concorda em cumprir e estar vinculado a estes Termos de Uso. Este aplicativo é de uso exclusivo dos vigilantes e equipe autorizada da Arena PlayZone.',
      'termos_secao2_tit': '2. Responsabilidades do Usuário',
      'termos_secao2_txt': 'O usuário é responsável por manter a confidencialidade de suas credenciais de login e por todas as atividades realizadas sob sua conta. É estritamente proibido compartilhar o acesso com terceiros não autorizados.',
      'termos_secao3_tit': '3. Propriedade Intelectual',
      'termos_secao3_txt': 'Todo o conteúdo, marcas registradas, logotipos e códigos-fonte deste aplicativo são de propriedade exclusiva da PlayZone. Nenhum direito de propriedade intelectual é transferido ao usuário.',

      // Política de Privacidade
      'privacidade_titulo': 'POLÍTICA DE PRIVACIDADE',
      'privacidade_atualizacao': 'Última atualização: 20/05/2026',
      'privacidade_secao1_tit': '1. Coleta de Informações',
      'privacidade_secao1_txt': 'Coletamos informações necessárias para a autenticação e registro das atividades de segurança, incluindo nome, e-mail, matrícula de vigilante, e logs de acessos realizados nas quadras.',
      'privacidade_secao2_tit': '2. Uso das Informações',
      'privacidade_secao2_txt': 'Os dados coletados são utilizados exclusivamente para garantir a segurança da arena, auditoria de acessos, comunicação com a equipe de suporte e melhorias no aplicativo.',
      'privacidade_secao3_tit': '3. Segurança dos Dados',
      'privacidade_secao3_txt': 'Implementamos medidas de segurança técnicas e organizacionais para proteger as informações contra acesso não autorizado, alteração, divulgação ou destruição.',

      // Splash Page
      'splash_carregando': 'Carregando o sistema...',

      // Controle de Acesso Screen
      'controle_escanear_qr': 'Escaneie o QR Code',
      'controle_posicione_qr': 'Posicione o QR Code do cliente para registrar a entrada.',
      'controle_botao_abrir_scanner': 'ABRIR SCANNER (SIMULAR)',
      'controle_entradas_recentes': 'Entradas recentes',
      'controle_ver_historico': 'Ver histórico completo',
      'controle_nenhuma_entrada': 'Nenhuma entrada registrada recentemente.',
      'controle_todos_dentro': 'Todos os clientes simulados já estão dentro da arena!',
      'controle_qr_identificado': 'QR Code Identificado',
      'controle_local_reservado': 'Local reservado:',
      'controle_horario_agendado': 'Horário agendado:',
      'controle_acesso_liberado': 'Acesso liberado para {nome}!',
    },
    'English': {
      // General / Common
      'vigilante': 'GUARD',
      'cancelar': 'Cancel',
      'confirmar': 'Confirm',
      'erro': 'Error',
      'sucesso': 'Success',
      'salvar': 'Save',
      'voltar': 'Back',
      'entendi': 'Understood',
      'ok': 'OK',
      'liberado': 'APPROVED',
      'pendente': 'PENDING',
      'livre': 'FREE',
      'em_uso': 'IN USE',
      'disponivel': 'AVAILABLE',
      'manutencao': 'MAINTENANCE',

      // Authentication
      'login_titulo': 'Welcome back!',
      'login_subtitulo': 'Enter your details to access your PlayZone account.',
      'email_rotulo': 'E-mail',
      'email_dica': 'e.g. player@email.com',
      'senha_rotulo': 'Password',
      'senha_dica': 'Enter your access password',
      'esqueci_senha': 'Forgot my password',
      'entrar': 'Sign In',
      'nao_tem_conta': "Don't have an account?",
      'cadastre_se': 'Sign Up',
      'validar_email_vazio': 'Please enter your e-mail',
      'validar_email_invalido': 'Please enter a valid e-mail',
      'validar_senha_vazio': 'Please enter your password',
      'validar_senha_tamanho': 'The password must contain at least 6 characters',

      'cadastro_titulo': 'Create Account',
      'cadastro_subtitulo': 'Fill in the details below to register as a Guard.',
      'nome_rotulo': 'Full Name',
      'nome_dica': 'Enter your full name',
      'matricula_rotulo': 'Registration ID',
      'matricula_dica': 'Enter registration number',
      'confirmar_senha_rotulo': 'Confirm Password',
      'confirmar_senha_dica': 'Enter the password again',
      'cadastrar': 'Register',
      'ja_tem_conta': 'Already have an account?',
      'entre': 'Log In',
      'validar_nome_vazio': 'Please enter your full name',
      'validar_nome_incompleto': 'Please enter first and last name',
      'validar_matricula_vazio': 'Please enter your registration number',
      'validar_matricula_numeros': 'Registration must contain numbers only',
      'validar_confirmacao_vazio': 'Please confirm your password',
      'validar_confirmacao_diferente': 'Passwords do not match',
      'email_ja_usado': 'This e-mail is already in use by another guard.',
      'cadastro_realizado': 'Registration Completed',
      'cadastro_sucesso_msg': 'Your guard account was successfully created! Log in to start.',

      'recuperar_senha_titulo': 'Recover Password',
      'recuperar_senha_subtitulo': 'Enter your registered e-mail to send reset instructions.',
      'enviar_instrucoes': 'Send Instructions',
      'voltar_login': 'Back to login',
      'email_nao_encontrado': 'E-mail not found',
      'email_enviado_titulo': 'E-mail Sent',
      'email_enviado_msg': 'Recovery e-mail successfully sent to: {email}. Check your inbox.',

      // Navigation Aba
      'aba_home': 'Home',
      'aba_buscar': 'Search',
      'aba_historico': 'History',
      'aba_perfil': 'Profile',

      // Home Screen
      'home_ola': 'Hello, {nome}! 👋',
      'home_pronto': 'Ready for another workday.',
      'home_escanear_qr': 'SCAN\nQR CODE',
      'home_registre_entrada': 'Register user check-ins',
      'home_atalhos': 'ARENA SHORTCUTS',
      'home_controle_acesso': 'ACCESS CONTROL',
      'home_gerencie_entradas': 'Manage and register arena entries',
      'home_status_arena': 'ARENA STATUS',
      'home_ocupacao_quadras': 'View occupancy and court situations',
      'home_historico_entradas': 'ENTRY HISTORY',
      'home_consulte_entradas': 'Check all registered check-ins',
      'home_buscar_usuarios': 'SEARCH USERS',
      'home_procure_documento': 'Search by name or document (CPF)',
      'home_instrucoes': 'INSTRUCTIONS FOR USE',
      'home_como_operar': 'How to operate the access system:',
      'home_passo1': 'Open the QR Code scanner when welcoming a player at the court entrance.',
      'home_passo2': 'Validate the reservation details shown on screen (player name, court, and time).',
      'home_passo3': 'Click \'Register Entry\' to grant access and update arena metrics.',
      'home_passo4': 'Check the \'Arena Status\' menu to monitor clients currently active on the courts.',
      'home_acao_principal': 'Main action',
      'home_tutorial_desc': 'Use the scanner to register user entries quickly and securely.',

      // Buscar Screen
      'buscar_titulo': 'SEARCH',
      'buscar_dica': 'Search by name, CPF, or registration...',
      'buscar_resultados': 'RESULTS',
      'buscar_sem_resultados': 'No results found.',

      // Histórico Screen
      'historico_titulo': 'ENTRY HISTORY',
      'filtro_hoje': 'Today',
      'filtro_ontem': 'Yesterday',
      'filtro_esta_semana': 'This week',
      'filtro_todos': 'All',
      'historico_busca_dica': 'Search by name or court...',
      'historico_sem_registros': 'No records found.',

      // Perfil Screen
      'perfil_titulo': 'MY PROFILE',
      'perfil_matricula': 'Registration ID: {matricula}',
      'perfil_configuracoes': 'Settings',
      'perfil_notificacoes': 'Notifications',
      'perfil_sobre': 'About the app',
      'perfil_sair_conta': 'Sign out',
      'perfil_confirmacao_titulo': 'Sign Out',
      'perfil_confirmacao_msg': 'Do you really want to sign out of your account?',
      'perfil_sair': 'Sign Out',

      // Notificações Screen
      'notif_titulo': 'NOTIFICATIONS',
      'notif_limpar_tudo': 'Clear all',
      'notif_sem_novas': 'You have no new notifications.',
      'notif_limpo_msg': 'Notification history cleared.',

      // Conversa / Chat Notificações
      'chat_titulo': 'CONVERSATION',
      'chat_suporte': 'PlayZone Support',
      'chat_dica': 'Type your message...',
      'chat_resposta_auto': 'Message received and recorded in the arena system.',

      // Status Arena Screen
      'status_ocupacao_geral': 'GENERAL OCCUPANCY',
      'status_quadras_em_uso': 'courts in use',
      'status_capacidade_maxima': 'MAX CAPACITY',
      'status_atletas_ativos': 'active athletes in the arena',
      'status_situacao_quadras': 'COURTS STATUS',
      'status_horario_previsto': 'Estimated time: {horario}',
      'status_partida_finalizada': 'Match finished successfully.',
      'status_manutencao_msg': 'Court under maintenance.',
      'status_liberada_msg': 'Court released successfully.',
      'status_botao_liberar': 'Release',
      'status_botao_concluir': 'Complete',
      'status_botao_manutencao': 'Maintenance',
      'status_botao_disponibilizar': 'Make Available',

      // Perfil Detalhado Screen
      'detalhes_titulo': 'PLAYER DETAILS',
      'detalhes_dados_cliente': 'CLIENT DATA',
      'detalhes_nome': 'Name',
      'detalhes_cpf': 'CPF',
      'detalhes_matricula': 'Registration ID',
      'detalhes_local': 'Reservation Location',
      'detalhes_horario': 'Estimated Time',
      'detalhes_status': 'ACCESS STATUS',
      'detalhes_acoes': 'Access Actions',
      'detalhes_btn_entrada': 'Register Entry',
      'detalhes_btn_saida': 'Register Exit',
      'detalhes_entrada_sucesso': 'Entry of {nome} registered.',
      'detalhes_saida_sucesso': 'Exit of {nome} registered.',

      // Sobre o aplicativo
      'sobre_titulo': 'ABOUT THE APP',
      'sobre_versao': 'Version 1.2.0',
      'sobre_nome_app': 'PlayZone Guard',
      'sobre_descricao': 'The PlayZone Guard app was developed to optimize access control and real-time monitoring of sports courts at the PlayZone Arena. With it, the security team can validate tickets via QR Code, track occupancy status, and manage athlete presence in an agile and secure way.',
      'sobre_desenvolvido_por': 'DEVELOPED BY',
      'sobre_equipe_ti': 'PlayZone IT Team',
      'sobre_documentos': 'Legal Documents',
      'sobre_termos': 'Terms of Use',
      'sobre_privacidade': 'Privacy Policy',

      // Termos de Uso
      'termos_titulo': 'TERMS OF USE',
      'termos_atualizacao': 'Last update: 2026-05-20',
      'termos_secao1_tit': '1. Acceptance of Terms',
      'termos_secao1_txt': 'By accessing and using the PlayZone Guard app, you agree to comply with and be bound by these Terms of Use. This app is for the exclusive use of guards and authorized staff of the PlayZone Arena.',
      'termos_secao2_tit': '2. User Responsibilities',
      'termos_secao2_txt': 'The user is responsible for maintaining the confidentiality of their login credentials and for all activities conducted under their account. Sharing access with unauthorized third parties is strictly prohibited.',
      'termos_secao3_tit': '3. Intellectual Property',
      'termos_secao3_txt': 'All content, trademarks, logos, and source code of this app are the exclusive property of PlayZone. No intellectual property rights are transferred to the user.',

      // Política de Privacidade
      'privacidade_titulo': 'PRIVACY POLICY',
      'privacidade_atualizacao': 'Last update: 2026-05-20',
      'privacidade_secao1_tit': '1. Information Collection',
      'privacidade_secao1_txt': 'We collect information necessary for authentication and logging of security activities, including name, e-mail, guard registration, and logs of court accesses.',
      'privacidade_secao2_tit': '2. Use of Information',
      'privacidade_secao2_txt': 'The collected data is used exclusively to guarantee arena security, audit accesses, communicate with support staff, and improve the app.',
      'privacidade_secao3_tit': '3. Data Security',
      'privacidade_secao3_txt': 'We implement technical and organizational security measures to protect information against unauthorized access, alteration, disclosure, or destruction.',

      // Splash Page
      'splash_carregando': 'Loading system...',

      // Controle de Acesso Screen
      'controle_escanear_qr': 'Scan the QR Code',
      'controle_posicione_qr': 'Position the client\'s QR Code to register the entry.',
      'controle_botao_abrir_scanner': 'OPEN SCANNER (SIMULATE)',
      'controle_entradas_recentes': 'Recent entries',
      'controle_ver_historico': 'View complete history',
      'controle_nenhuma_entrada': 'No entries registered recently.',
      'controle_todos_dentro': 'All simulated clients are already inside the arena!',
      'controle_qr_identificado': 'QR Code Identified',
      'controle_local_reservado': 'Reserved location:',
      'controle_horario_agendado': 'Scheduled time:',
      'controle_acesso_liberado': 'Access granted for {nome}!',
    },
    'Español': {
      // General / Common
      'vigilante': 'VIGILANTE',
      'cancelar': 'Cancelar',
      'confirmar': 'Confirmar',
      'erro': 'Error',
      'sucesso': 'Éxito',
      'salvar': 'Guardar',
      'voltar': 'Volver',
      'entendi': 'Entendido',
      'ok': 'OK',
      'liberado': 'LIBERADO',
      'pendente': 'PENDIENTE',
      'livre': 'LIBRE',
      'em_uso': 'EN USO',
      'disponivel': 'DISPONIBLE',
      'manutencao': 'MANTENIMIENTO',

      // Authentication
      'login_titulo': '¡Bienvenido de nuevo!',
      'login_subtitulo': 'Ingrese sus datos para acceder a su cuenta de PlayZone.',
      'email_rotulo': 'Correo electrónico',
      'email_dica': 'Ej: jugador@email.com',
      'senha_rotulo': 'Contraseña',
      'senha_dica': 'Ingrese su contraseña de acesso',
      'esqueci_senha': 'Olvidé mi contraseña',
      'entrar': 'Entrar',
      'nao_tem_conta': '¿No tienes una cuenta?',
      'cadastre_se': 'Regístrate',
      'validar_email_vazio': 'Por favor, ingrese su correo electrónico',
      'validar_email_invalido': 'Por favor, ingrese un correo electrónico válido',
      'validar_senha_vazio': 'Por favor, ingrese su contraseña',
      'validar_senha_tamanho': 'La contraseña debe contener al menos 6 caracteres',

      'cadastro_titulo': 'Crear Cuenta',
      'cadastro_subtitulo': 'Complete los datos a continuación para registrarse como Vigilante.',
      'nome_rotulo': 'Nombre Completo',
      'nome_dica': 'Ingrese su nombre completo',
      'matricula_rotulo': 'Matrícula',
      'matricula_dica': 'Ingrese el número de matrícula',
      'confirmar_senha_rotulo': 'Confirmar Contraseña',
      'confirmar_senha_dica': 'Ingrese la contraseña nuevamente',
      'cadastrar': 'Registrarse',
      'ja_tem_conta': '¿Ya tienes una cuenta?',
      'entre': 'Inicia sesión',
      'validar_nome_vazio': 'Por favor, ingrese su nombre completo',
      'validar_nome_incompleto': 'Por favor, ingrese nombre y apellido',
      'validar_matricula_vazio': 'Por favor, ingrese su matrícula',
      'validar_matricula_numeros': 'La matrícula debe contener solo números',
      'validar_confirmacao_vazio': 'Por favor, confirme su contraseña',
      'validar_confirmacao_diferente': 'Las contraseñas no coinciden',
      'email_ja_usado': 'Este correo electrónico ya está siendo utilizado por otro vigilante.',
      'cadastro_realizado': 'Registro Realizado',
      'cadastro_sucesso_msg': '¡Su cuenta de vigilante ha sido creada con éxito! Inicie sesión para comenzar.',

      'recuperar_senha_titulo': 'Recuperar Contraseña',
      'recuperar_senha_subtitulo': 'Ingrese su correo electrónico registrado para enviar las instrucciones de restablecimiento.',
      'enviar_instrucoes': 'Enviar Instrucciones',
      'voltar_login': 'Voltar para o login',
      'email_nao_encontrado': 'Correo electrónico no encontrado',
      'email_enviado_titulo': 'Correo Enviado',
      'email_enviado_msg': 'Correo electrónico de recuperación enviado con éxito a: {email}. Revise su bandeja de entrada.',

      // Navigation Aba
      'aba_home': 'Inicio',
      'aba_buscar': 'Buscar',
      'aba_historico': 'Historial',
      'aba_perfil': 'Perfil',

      // Home Screen
      'home_ola': '¡Hola, {nome}! 👋',
      'home_pronto': 'Listo para otro día de trabajo.',
      'home_escanear_qr': 'ESCANEAR\nCÓDIGO QR',
      'home_registre_entrada': 'Registre la entrada de usuarios',
      'home_atalhos': 'ATAJOS DE LA ARENA',
      'home_controle_acesso': 'CONTROL DE ACCESO',
      'home_gerencie_entradas': 'Gestione y registre entradas en la arena',
      'home_status_arena': 'ESTADO DE LA ARENA',
      'home_ocupacao_quadras': 'Ver ocupación y situación de las canchas',
      'home_historico_entradas': 'HISTORIAL DE ENTRADAS',
      'home_consulte_entradas': 'Consulte todas las entradas registradas',
      'home_buscar_usuarios': 'BUSCAR USUARIOS',
      'home_procure_documento': 'Busque por nombre o documento (CPF)',
      'home_instrucoes': 'INSTRUCCIONES DE USO',
      'home_como_operar': 'Cómo operar el sistema de accesos:',
      'home_passo1': 'Abra el escáner de código QR al recibir a un jugador en la entrada de la cancha.',
      'home_passo2': 'Valide los datos de la reserva presentados en pantalla (nombre del jugador, cancha y horario).',
      'home_passo3': 'Haga clic en \'Registrar Entrada\' para liberar el acceso y actualizar las métricas de la arena.',
      'home_passo4': 'Consulte el menú \'Estado de la Arena\' para monitorear a los clientes actualmente activos en las canchas.',
      'home_acao_principal': 'Acción principal',
      'home_tutorial_desc': 'Use el escáner para registrar la entrada de usuarios de forma rápida y segura.',

      // Buscar Screen
      'buscar_titulo': 'BUSCAR',
      'buscar_dica': 'Buscar por nombre, CPF o matrícula...',
      'buscar_resultados': 'RESULTADOS',
      'buscar_sem_resultados': 'No se encontraron resultados.',

      // Histórico Screen
      'historico_titulo': 'HISTORIAL DE ENTRADAS',
      'filtro_hoje': 'Hoy',
      'filtro_ontem': 'Ayer',
      'filtro_esta_semana': 'Esta semana',
      'filtro_todos': 'Todos',
      'historico_busca_dica': 'Buscar por nombre o cancha...',
      'historico_sem_registros': 'Ningún registro encontrado.',

      // Perfil Screen
      'perfil_titulo': 'MI PERFIL',
      'perfil_matricula': 'Matrícula: {matricula}',
      'perfil_configuracoes': 'Configuración',
      'perfil_notificacoes': 'Notificaciones',
      'perfil_sobre': 'Sobre la aplicación',
      'perfil_sair_conta': 'Cerrar sesión',
      'perfil_confirmacao_titulo': 'Cerrar Sesión',
      'perfil_confirmacao_msg': '¿Realmente desea cerrar sesión?',
      'perfil_sair': 'Salir',

      // Notificações Screen
      'notif_titulo': 'NOTIFICACIONES',
      'notif_limpar_tudo': 'Limpiar todo',
      'notif_sem_novas': 'No tiene nuevas notificaciones.',
      'notif_limpo_msg': 'Historial de notificaciones limpio.',

      // Conversa / Chat Notificações
      'chat_titulo': 'CONVERSACIÓN',
      'chat_suporte': 'Soporte PlayZone',
      'chat_dica': 'Escriba su mensaje...',
      'chat_resposta_auto': 'Mensaje recibido y registrado en el sistema de la arena.',

      // Status Arena Screen
      'status_ocupacao_geral': 'OCUPACIÓN GENERAL',
      'status_quadras_em_uso': 'canchas en uso',
      'status_capacidade_maxima': 'CAPACIDADE MÁXIMA',
      'status_atletas_ativos': 'atletas activos en la arena',
      'status_situacao_quadras': 'ESTADO DE LAS CANCHAS',
      'status_horario_previsto': 'Horario previsto: {horario}',
      'status_partida_finalizada': 'Partida finalizada con éxito.',
      'status_manutencao_msg': 'Cancha en mantenimiento.',
      'status_liberada_msg': 'Cancha liberada con éxito.',
      'status_botao_liberar': 'Liberar',
      'status_botao_concluir': 'Concluir',
      'status_botao_manutencao': 'Mantenimiento',
      'status_botao_disponibilizar': 'Habilitar',

      // Perfil Detalhado Screen
      'detalhes_titulo': 'DETALLES DEL JUGADOR',
      'detalhes_dados_cliente': 'DATOS DEL CLIENTE',
      'detalhes_nome': 'Nombre',
      'detalhes_cpf': 'CPF',
      'detalhes_matricula': 'Matrícula',
      'detalhes_local': 'Lugar de la Reserva',
      'detalhes_horario': 'Horario Previsto',
      'detalhes_status': 'ESTADO DE ACCESO',
      'detalhes_acoes': 'Acciones de Acceso',
      'detalhes_btn_entrada': 'Registrar Entrada',
      'detalhes_btn_saida': 'Registrar Salida',
      'detalhes_entrada_sucesso': 'Entrada de {nome} registrada.',
      'detalhes_saida_sucesso': 'Salida de {nome} registrada.',

      // Sobre o aplicativo
      'sobre_titulo': 'SOBRE LA APLICACIÓN',
      'sobre_versao': 'Versión 1.2.0',
      'sobre_nome_app': 'PlayZone Vigilante',
      'sobre_descricao': 'La aplicación PlayZone Vigilante fue desarrollada para optimizar el control de acceso y monitoreo en tempo real de las canchas deportivas de la Arena PlayZone. Con ella, el equipo de seguridad puede validar boletos mediante código QR, realizar un seguimiento del estado de ocupación y gestionar la presencia de atletas de manera ágil y segura.',
      'sobre_desenvolvido_por': 'DESARROLLADO POR',
      'sobre_equipe_ti': 'Equipo de TI de PlayZone',
      'sobre_documentos': 'Documentos Legales',
      'sobre_termos': 'Términos de Uso',
      'sobre_privacidade': 'Política de Privacidad',

      // Termos de Uso
      'termos_titulo': 'TÉRMINOS DE USO',
      'termos_atualizacao': 'Última actualización: 20/05/2026',
      'termos_secao1_tit': '1. Aceptación de los Términos',
      'termos_secao1_txt': 'Al acceder y utilizar la aplicación PlayZone Vigilante, usted acepta cumplir y estar sujeto a estos Términos de uso. Esta aplicación es para uso exclusivo de vigilantes y personal autorizado de la Arena PlayZone.',
      'termos_secao2_tit': '2. Responsabilidades del Usuario',
      'termos_secao2_txt': 'El usuario es responsable de mantener la confidencialidad de sus credenciales de inicio de sesión y de todas las actividades realizadas bajo su cuenta. Está estrictamente prohibido compartir el acceso con terceros no autorizados.',
      'termos_secao3_tit': '3. Propiedad Intelectual',
      'termos_secao3_txt': 'Todo el contenido, marcas comerciales, logotipos y códigos fuente de esta aplicación son propiedad exclusiva de PlayZone. No se transfiere ningún derecho de propiedad intelectual al usuario.',

      // Política de Privacidade
      'privacidade_titulo': 'POLÍTICA DE PRIVACIDAD',
      'privacidade_atualizacao': 'Última actualización: 20/05/2026',
      'privacidade_secao1_tit': '1. Recopilación de Información',
      'privacidade_secao1_txt': 'Recopilamos la información necesaria para la autenticación y el registro de las actividades de seguridad, incluidos el nombre, el correo electrónico, la matrícula del vigilante y los registros de acceso a las canchas.',
      'privacidade_secao2_tit': '2. Uso de la Información',
      'privacidade_secao2_txt': 'Los datos recopilados se utilizan exclusivamente para garantizar la seguridad de la arena, auditar los accesos, comunicarse con el personal de soporte y mejorar la aplicación.',
      'privacidade_secao3_tit': '3. Seguridad de los Datos',
      'privacidade_secao3_txt': 'Implementamos medidas de seguridad técnicas y organizativas para proteger la información contra el acceso no autorizado, alteración, divulgación o destrucción.',

      // Splash Page
      'splash_carregando': 'Cargando el sistema...',

      // Controle de Acesso Screen
      'controle_escanear_qr': 'Escanee el código QR',
      'controle_posicione_qr': 'Posicione el código QR del cliente para registrar la entrada.',
      'controle_botao_abrir_scanner': 'ABRIR ESCÁNER (SIMULAR)',
      'controle_entradas_recentes': 'Entradas recientes',
      'controle_ver_historico': 'Ver historial completo',
      'controle_nenhuma_entrada': 'Ninguna entrada registrada recientemente.',
      'controle_todos_dentro': '¡Todos los clientes simulados ya están dentro de la arena!',
      'controle_qr_identificado': 'Código QR Identificado',
      'controle_local_reservado': 'Lugar reservado:',
      'controle_horario_agendado': 'Horario programado:',
      'controle_acesso_liberado': '¡Acceso liberado para {nome}!',
    }
  };

  static String obter(String chave, {Map<String, String>? parametros}) {
    final idioma = EstadoCentral().idiomaSelecionado;
    String texto = _dicionario[idioma]?[chave] ?? chave;

    if (parametros != null) {
      parametros.forEach((pChave, pValor) {
        texto = texto.replaceAll('{$pChave}', pValor);
      });
    }

    return texto;
  }
}
